### ISSUE TITLE
Email Verified At?

### ISSUE THREAD

**Issue by brandon-9** [laravel-frontend-presets/tall#101]
So the users table populates with the column email_vereified_at, but doesn't appear to be enabled within this by default? What's the best way to set that up? Does some of it already exist and is just not enabled? Thanks!

**Comment by rydurham** [comment]
To opt your user model into email verification you have to add `implements Illuminate\Contracts\Auth\MustVerifyEmail` to the model class.

See more here: https://laravel.com/docs/8.x/verification

**Comment by brandon-9** [comment]
Thank you @rydurham !
