### ISSUE TITLE
Updating to Laravel 9 and PHP 8.1

### ISSUE THREAD

**Issue by crazedVic** [laravel-frontend-presets/tall#102]
Problem 1
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.
    - Root composer.json requires laravel-frontend-presets/tall 4.0.0 -> satisfiable by laravel-frontend-presets/tall[v4.0.0].
    - [...]
    - laravel-frontend-presets/tall v4.0.0 requires illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it

Commenting out:
"laravel-frontend-presets/tall": "4.0.0"

Resolves the issue, as in composer updates fine, but then the app stops working, of course.

Solution:
Update dependency to Illuminate/Support 9?

**Comment by danharrin** [comment]
This has been done now :)

**Comment by crazedVic** [comment]
Thanks!
