### ISSUE TITLE
I updated all packages in my Laravel and it's still Tailwind 2.

### ISSUE THREAD

**Issue by core45** [laravel-frontend-presets/tall#109]
I updated all packages in my Laravel and it's still Tailwind 2.
I even did php artisan ui tall and it's still the same. 
It is not upgrading to Tailwind v.3

_Originally posted by @core45 in https://github.com/laravel-frontend-presets/tall/issues/108#issuecomment-1067840185_

**Comment by ryangjchandler** [comment]
@core45 Updating the package doesn't update the Tailwind version, you need to do that upgrade yourself. This package provides a starter kit that you publish into your application - after that point, it's your responsibility to upgrade the packages.

**Comment by core45** [comment]
So I did totally fresh install and it's still Tailwind 2

**Comment by ryangjchandler** [comment]
Whay version of this package are you installing?
