### ISSUE TITLE
Fresh install still has Tailwind v2

### ISSUE THREAD

**Issue by core45** [laravel-frontend-presets/tall#110]
I installed totally fresh Laravel 8
`laravel install test`

Then I installed this package as described in the read.me and it's still the same. It installs Tailwind v.2 instead of v.3

**Comment by ryangjchandler** [comment]
If you're on Laravel 8, you won't be able to use the latest version. New versions of the package only support Laravel 9.

**Comment by core45** [comment]
Would be nice if you put ANY information about it in the read.me 
I lost 2 days trying to make it work. Shit man!

**Comment by danharrin** [comment]
This is a preset for new projects, all new Laravel projects should be using v9.
