### ISSUE TITLE
Presets with laravel/ui in a laravel 9 jetstream project?

### ISSUE THREAD

**Issue by fpolli** [laravel-frontend-presets/tall#111]
I see that this has you install the laravel ui package which the laravel 9 docs say has been replaced by jetstream. I am using laravel 9 and jetstream, will this package cause conflicts?

**Comment by mortenebak** [comment]
This preset is intended to be installed into a fresh Laravel application. 
So either you use this package or jetstream to scaffold the login/auth features I guess :)
