### ISSUE TITLE
Broken!! after Laravel 9.19 update due to Vite I guess.

### ISSUE THREAD

**Issue by RAugadh** [laravel-frontend-presets/tall#114]
requires VITE integration to work again .

**Comment by danharrin** [comment]
Unfortunately, fixing this is not a priority for me right now as I am not actively using the preset, but I would accept a PR to fix this. Thanks!

**Comment by RAugadh** [comment]
Can You add the labels ,
I don't know how to do it, still learning

**Comment by Supernova3339** [comment]
My way was to just configure the path the preset puts css and js to within vite config file, then execute 'npm run build' 
This will run npm vite build which will  compile your assets for your application.

**Comment by kustomrtr** [comment]
@danharrin Hey, I just made PR to fix this issue. #115

**Comment by danharrin** [comment]
This is now added in #115 and v5 has been released, thanks @kustomrtr
