### ISSUE TITLE
Code didn’t merged

### ISSUE THREAD

**Issue by Blinks44** [laravel-frontend-presets/tall#121]
Can anyone explain to me: in stubs/**/app.js we have merged commit with replacing ```require bootstrap``` with ``` import bootstrap ```, but when we create fresh application with tall stack preset, it has old code with ```require ```

![D37341FE-0621-47C6-AF18-AF0C80A9B192](https://user-images.githubusercontent.com/8570193/206864442-c7394782-3e05-47e3-aea3-ea2012ff9fe4.png)

**Comment by ryangjchandler** [comment]
Because that code hasn't been released yet. I'll tag a release now.

**Comment by ryangjchandler** [comment]
Please update to 5.0.2 and install again.
