### ISSUE TITLE
Livewire component not found after initial setup

### ISSUE THREAD

**Issue by A-Ramsey** [laravel-frontend-presets/tall#135]
Just did the initial setup of the tall stack with auth but i keep getting component not found. Everything is connected and the db is set up and working. Cannot figure out why its not working, I haven't added any code etc just connected to the database.

Stack trace below for error
https://flareapp.io/share/pPvMXJ9m#context-livewire-component

**Comment by danharrin** [comment]
LW3 uses `App/Livewire` instead of `App/Http/Livewire` so I think it just needs to be migrated.

**Comment by moayad-tarig** [comment]
so what the solution ?

**Comment by eduardohpaludo** [comment]
I have the same problem

**Comment by kieranmcclure** [comment]
The package will need to be updated to accommodate for Livewire 3's new namespace, https://livewire.laravel.com/docs/upgrading#new-class-namespace

A work around for this at the moment is to configure Livewire to use the old Namespace, 

1. Make sure you have your Livewire configuration published with **php artisan livewire:publish --config**
2. Edit your config file and change class_namespace from 'App\\Livewire' to **'App\\Http\\Livewire**
3. Re-build your project and run **php artisan optimize && php artisan optimize:clear**

This should sort any issues you're having, tested on a clean project.

**Comment by jamie-brown** [comment]
Yep. I just used the livewire upgrade command: `php artisan livewire:upgrade`, which walks you through a migration that will automate most of this for you.

**Comment by danharrin** [comment]
Someone has a PR open (#132) but the tests are failing, if anyone fancies trying to fix it then I will merge their PR

**Comment by benshawuk** [comment]
I went through the upgrade steps and now authentication functionality has gone.

**Comment by danharrin** [comment]
Fixed by #132.
