### ISSUE TITLE
New Laravel version problem

### ISSUE THREAD

**Issue by Alexis-Arduca** [laravel-frontend-presets/tall#151]
With Laravel 11, laravel-frontend-presets/tall is no longer supported. Here is my error message. Can you fix this ?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-frontend-presets/tall ^7.0.2 -> satisfiable by laravel-frontend-presets/tall[v7.0.2].
    - Conclusion: don't install laravel/framework v11.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.1 (conflict analysis result)
    - laravel-frontend-presets/tall v7.0.2 requires illuminate/support ^10.0 -> satisfiable by illuminate/support[v10.0.0, ..., v10.48.2].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0-beta.1, ..., v9.52.16, v10.0.0, ..., v10.48.2, v11.0.0, ..., v11.0.5], laravel/framework[v11.0.0, ..., v11.0.5]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.0.5].

**Comment by ryangjchandler** [comment]
Laravel 11.x support hasn't been added yet @Alexis-Arduca. Please be patient, we will get to this soon.

**Comment by Alexis-Arduca** [comment]
Great ! Thank you very much for the quick response !
