### ISSUE TITLE
Why isn't this repo a template repo

### ISSUE THREAD

**Issue by Visnicio** [laravel-frontend-presets/tall#160]
I was about to start experimenting with the TALL stack and noticed that the "template repo" is not actually a template repo (like the ones that provide a "Use this template" button)

Why is that?

**Comment by Visnicio** [comment]
nvm, just realized is not a laravel app by default

**Comment by imliam** [comment]
It's an installable package that sets up your application based on templates - the repo itself isn't meant to be used as a template.

That said, GitHub templates basically fork the repo, you can do that if you really want to.
