### ISSUE TITLE
First and Last Name Auth

### ISSUE THREAD

**Issue by daugaard47** [laravel-frontend-presets/tall#19]
How do you change the auth on registration to allow for first and last name, rather Only name?
Really new to Livewire. Appreciate any help.

Get the followinf Error:

> Unable to set component data. Public property [$last_name] not found on component: [auth.register]
vendor\livewire\livewire\src\ComponentConcerns\HandlesActions.php:30

**Comment by DanHarrin** [comment]
Hey! Could you post your registration component class and view for us please?

**Comment by daugaard47** [comment]
Never mind I'm an idiot. 🤦‍♂️ Just figured it out. 

On registration component I forgot to change / add in the new variables
```
    public $first_name = '';

    public $last_name = ''; 
```

Please delete this post. LOL

**Comment by DanHarrin** [comment]
Aha not to worry 😄
