### ISSUE TITLE
Login form error with autofill password managers

### ISSUE THREAD

**Issue by booni3** [laravel-frontend-presets/tall#23]
Password managers fill both the email and password at the same time. It causes odd behaviour on desktop (flickering) and on iOS it causes the password filling to be completely broken. I have added some more detail on the livewire repo (https://github.com/livewire/livewire/issues/943).

The issue above does not use this preset, but I have since tried it and have the same issues.

I believe the core issue is that we are data binding the email/password via livewire but actually we only really need to send the data with the form submit.

**Comment by DanHarrin** [comment]
Closing this issue as it will be dealt with in livewire/livewire#943. Thanks for the report.
