### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by lucaros97** [laravel-frontend-presets/tall#34]
After a fresh install using the command:
`composer require livewire/livewire laravel-frontend-presets/tall`

I can't run the command:
`php artisan ui tall` because I get `Could not open input file: artisan`

Previously I was able to do it (its not the first time I us TALL)

**Comment by DanHarrin** [comment]
Sounds like you're running the command in the wrong directory? 🤨 

Just check it's definitely your project root please.

**Comment by lucaros97** [comment]
Definitely the root directory:
<img width="1451" alt="Schermata 2020-05-23 alle 09 47 01" src="https://user-images.githubusercontent.com/8333004/82725022-67699e00-9cda-11ea-8580-02f48b44158a.png">

**Comment by DanHarrin** [comment]
Please follow the steps on how to install the Laravel project structure as well - https://github.com/laravel-frontend-presets/tall/issues/34.

Unfortunately it's not enough to just require the framework.

**Comment by lucaros97** [comment]
You're right!
Just missed that 🤦‍♂️

**Comment by lucaros97** [comment]
#35 Created a pull request for "beginners" to avoid them forget to do it!

**Comment by imliam** [comment]
#35 merged
