### ISSUE TITLE
Fresh install - Tailwind render problem

### ISSUE THREAD

**Issue by elbaylot** [laravel-frontend-presets/tall#40]
Hello,
Thank you for this package which looks interesting. 

I followed all the installation steps but there seems to be a problem with the rendering when I run `php artisan serve`. I didn't make any other extra modifications ...

I've never used Tailwind so do I have to do something special to get the rendering right ?

![image](https://user-images.githubusercontent.com/27012416/85281305-0aecd080-b48a-11ea-907a-5aa7702bff32.png)

Thanks a lot for this inappropriate / incongruous issue

**Comment by elbaylot** [comment]
Ok sorry i forget to run `npx tailwindcss build styles.css -o output.css` at the end of process 🥇

**Comment by DanHarrin** [comment]
Hey @elbaylot, you should instead use `npm run dev` to compile all assets using Laravel Mix, including Tailwind. No extra setup is required.
