### ISSUE TITLE
Custom redirect  after login / Register

### ISSUE THREAD

**Issue by techguydev** [laravel-frontend-presets/tall#48]
Hi

Thanks for this package.

I would like to redirect  to the previous  page when a user login or register just like mentioned in this article:

https://stackoverflow.com/questions/42326430/how-to-redirect-to-previous-page-after-successful-register-in-laravel

how can it be implemented using livewire in the login/register?

**Comment by ryangjchandler** [comment]
Hi @techguydev - the Livewire components with this preset are published so you can just change the redirect in the Login component class to `redirect()->back()` instead of `redirect(route('home'))`

**Comment by imliam** [comment]
On this note I've just changed the default behaviour to redirect to the intended route after login and registration #50

**Comment by techguydev** [comment]
Thanks @imliam  I appreciate it.

**Comment by techguydev** [comment]
@imliam  I have tried making the changes you suggested but it is not redirecting to the previos page

**Comment by techguydev** [comment]
it is just not working for me I even try to test if there is some session info in the mount method of the register component and it always returns null @ryangjchandler  @imliam

**Comment by techguydev** [comment]
it looks like that inside the Register controller the system is not able to get the Session previous.url variable.

This is how I have managed to make it work:

In the register  and login components I have set

```
public previewsUrl='/'
```

```
 public function Mount ()
    {
       $this->previousUrl=\Session::get('_previous.url');

    }

 public function authenticate()
    {
        $credentials = $this->validate([
            'email' => ['required', 'email'],
            'password' => ['required'],
        ]);

        if (!Auth::attempt($credentials, $this->remember)) {
            $this->addError('email', trans('auth.failed'));

            return;
        }

        redirect()->to($this->previousUrl);

    }
```

**Comment by daugaard47** [comment]
@techguydev  Thank you so much for solving this. That worked great.
I had to make 2 small edits:

Changed `public previewsUrl='/'` to `public $previousUrl='/';`

And then used Session like this:
```
public function mount ()
    {
        $this->previousUrl=\session('_previous.url');
    }
```

Works perfect for Login and Registration!
Thanks Again!

**Comment by techguydev** [comment]
@daugaard47 nice to hear it worked for you too.
