### ISSUE TITLE
Route [home] not defined. 

### ISSUE THREAD

**Issue by rabol** [laravel-frontend-presets/tall#49]
Hi

Just did a fresh laravel installation and then followed the installation of this preset, and when I try access the site I got this:

Route [home] not defined. (View: /home/vagrant/code/tall/resources/views/welcome.blade.php)

Did I miss something?

**Comment by SilverPaladin** [comment]
The route is defined in web.php. Do you see the route there on line 16?
`Route::view('/', 'welcome')->name('home');`

**Comment by imliam** [comment]
The named route was only added to the auth scaffolding, not the default one. I've just added it to the default scaffolding in this commit 93ab258

Thanks for reporting the issue!
