### ISSUE TITLE
RedirectIfAuthenticated overrides CONST /home

### ISSUE THREAD

**Issue by dillingham** [laravel-frontend-presets/tall#52]
Not sure if this is intended or not
RedirectIfAuthenticated overrides CONST /home
But I don't have a default named route either
Not sure either of those make sense to change
Maybe remove it from the provider & test for non auth?
<img width="1280" alt="Screen Shot 2020-07-20 at 11 38 38 PM" src="https://user-images.githubusercontent.com/29180903/88010188-4f4baa80-cae2-11ea-8a54-2f1d4d613081.png">

**Comment by imliam** [comment]
I've just tagged a new version that includes a default named route in the non-auth stubs which fixes this: https://github.com/laravel-frontend-presets/tall/releases/tag/v1.7.3

**Comment by dillingham** [comment]
@imliam thanks Liam
