### ISSUE TITLE
Implementing email verification with TALL Preset

### ISSUE THREAD

**Issue by fawzanm** [laravel-frontend-presets/tall#55]
I've checked the docs and tried some hacks as well, but still, I couldn't figure out a way to protect the dashboard with `verify` email methods.

In laravel/ui preset we achieve this with `Auth::routes(['verify' => true]);`. But I am not sure how to obtain this behaviour with the routes registered with the tall preset. 

Is there any workaround for this?

**Comment by imliam** [comment]
Because this preset publishes the routes to your own `routes/web.php` directory, you can protect routes with the regular email verification middleware if you want; `->middleware('verified')`

https://laravel.com/docs/7.x/verification#protecting-routes
