### ISSUE TITLE
 Attribute [layout] does not exist.

### ISSUE THREAD

**Issue by gotyourchalk** [laravel-frontend-presets/tall#60]
getting this issue after a fresh install and installing auth

**Comment by cgenesis** [comment]
Same here, fresh install, tried to run "php artisan serve" and got this:

![image](https://user-images.githubusercontent.com/20626513/92432252-0a520500-f170-11ea-8659-5bb2a2f0ed89.png)

**Comment by ryangjchandler** [comment]
Which version of Livewire are you using? The package still needs to be updated to support v2.

**Comment by Elshaden** [comment]
Same problem, 
composer require livewire/livewire laravel-frontend-presets/tall

installs by default the latest version of Livewire.... should fix this if updating to V2 is taking its time, also note the upcoming Laravel V8...

Thanks for the nice package.. I used with Livewire V1 and works like magic... thanks

**Comment by imliam** [comment]
Livewire v2 support is coming: #61 

If you want to keep using Livewire v1, just make sure to `composer require livewire/livewire:^1.0` for now
