### ISSUE TITLE
User registration test incompatibility with Livewire 2.2.4

### ISSUE THREAD

**Issue by michaeldyrynda** [laravel-frontend-presets/tall#65]
This is just to flag livewire/livewire#1635 for a regression in how Livewire 2.2.4 handles validation rules, in case anybody hits it with a new app.

It means that, out of the box, the registration test will fail as Livewire no longer passes the `passwordConfirmation` property to the validation rules unless explicitly keyed in the rules.

The current userland workaround would be to update the validation rule:

```diff
$this->validate([
     'name' => ['required'],
     'email' => ['required', 'email', 'unique:users'],
-    'password' => ['required', 'min:8', 'same:passwordConfirmation'],
+    'password' => ['required', 'min:8'],
+    'passwordConfirmation' => ['same:password'],
]);

**Comment by michaeldyrynda** [comment]
This is also affecting the `Reset` component and `ResetTest` in the same manner.

**Comment by ryangjchandler** [comment]
Thanks for flagging this @michaeldyrynda - looks like your PR was merged and this issue can be closed now. Thanks again!

**Comment by michaeldyrynda** [comment]
I meant to come back and close this 😅
