### ISSUE TITLE
Can't we use it in L7?

### ISSUE THREAD

**Issue by tpaksu** [laravel-frontend-presets/tall#69]
Hi, 

I am developing a project with Laravel 7 and decided to upgrade it to Livewire 2. Then I realized my current TALL stack didn't have the route modifications (`Route::livewire` -> `Route::get`) and I decided to upgrade it too. Then I couldn't. Because It has `Illuminate\Support:^8.0` as a dependency, and I have ^7.0. Should I upgrade framework too to use LW2? (I hope it has a easier solution)

BTW, Livewire 2 has `"illuminate/support": "^7.0|^8.0",` in it's `composer.json`. Do you have anything special which only contains in Laravel 8?

Thanks.

**Comment by ryangjchandler** [comment]
The preset itself only supports Laravel 8 & Livewire 2. 

When you run the preset though it publishes everything into your application, so for the routes, you can change them yourself in the `routes/web.php` file. There's no need to keep the preset around after running it.

**Comment by tpaksu** [comment]
Hi Ryan,

Thanks for the heads up! I removed the preset and everything is intact. I can happily upgrade to LW2 now :)

Have a nice evening! 👍
