### ISSUE TITLE
Red input fields in Firefox

### ISSUE THREAD

**Issue by Wulfheart** [laravel-frontend-presets/tall#7]
At first thanks for this amazing package.

By default all input fields are red (aka invalid) on Firefox. This problem doesn't exist on chrome.
![grafik](https://user-images.githubusercontent.com/25671390/81385727-25562f00-9114-11ea-8f72-962f50bdabb6.png)

**Comment by DanHarrin** [comment]
Very odd, I can replicate. I'll take a look into this.

**Comment by DanHarrin** [comment]
Looks like this is being caused by the "required" attribute on our inputs, although I'm not sure why.

**Comment by julienbourdeau** [comment]
I have noticed the same thing in the Laravel Vapor UI and I don't think it's built with Livewire (not sure tho).
