### ISSUE TITLE
Add slot for Full-Page Components

### ISSUE THREAD

**Issue by iAmKevinMcKee** [laravel-frontend-presets/tall#71]
Would you accept a PR that adds a `{{ $slot }}` in the `app.blade.php` file so you could easily use Full Page Components out of the box?

**Comment by imliam** [comment]
I could swear we already had that - but looks like it was only ever applied to the `layouts/auth.blade.php` - it'd be good to have symmetry with `layouts/app.blade.php` here.

**Comment by ryangjchandler** [comment]
Closed by #72.
