### ISSUE TITLE
The Mix manifest does not exist.

### ISSUE THREAD

**Issue by QuentinWatt** [laravel-frontend-presets/tall#74]
There seems to be a problem with the laravel-mix-tailwind package, which in turn also prevents the mix manifest from being generated.

```
ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: laravel-mix@5.0.7
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^5.0.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^2.1.7" from laravel-mix-tailwind@0.1.1
npm ERR! node_modules/laravel-mix-tailwind
npm ERR!   laravel-mix-tailwind@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/quentin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/quentin/.npm/_logs/2020-11-05T10_24_54_803Z-debug.log
```

Not sure how to work around this.

**Comment by marcorieser** [comment]
Which npm version are you using?

**Comment by nakhate** [comment]
I am using npm version 7.0.8. This is a fresh install of Laravel 8. I encountered the same issue. Error output below:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: laravel-mix@5.0.9
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^5.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^2.1.7" from laravel-mix-tailwind@0.1.1
npm ERR! node_modules/laravel-mix-tailwind
npm ERR!   dev laravel-mix-tailwind@"^0.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/dan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dan/.npm/_logs/2020-12-03T13_59_20_427Z-debug.log

**Comment by nakhate** [comment]
~Workaround

Step 1. npm install --force
Step 2. npm run dev
Step 3. npm install && npm run dev

**Comment by K2ouMais** [comment]
This workaround doesnt work.

**Comment by cnngraphics** [comment]
Does not work
![image](https://user-images.githubusercontent.com/1514378/103485707-4e73b000-4dc6-11eb-96eb-770aea67c609.png)

**Comment by cnngraphics** [comment]
This worked for me
 updates npm to latest
``` npm install -g npm@latest  ```
``` npm install 
npm run dev ```

**Comment by danharrin** [comment]
Hey! Let us know if this issue still persists with v3.0.0.

**Comment by ryatkins** [comment]
`npm install -g npm@latest` worked for me, but took multiple times of running `npm install` to be able to finally run `npm run dev`

I'm getting these warnings still:

```
@tailwindcss/typography@0.2.0 requires a peer of tailwindcss@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN laravel-mix-tailwind@0.1.1 requires a peer of laravel-mix@^2.1.7 but none is installed. You must install peer dependencies yourself.
```
