### ISSUE TITLE
Update Tailwind to existing app

### ISSUE THREAD

**Issue by dcblogdev** [laravel-frontend-presets/tall#75]
Sorry if this is a dumb question but how do you update tailwind to the latest version for an existing application?

I want to use Tailwind animations that requires v1.6.0+

**Comment by ryangjchandler** [comment]
@dcblogdev You just need to update the version in the package.json file, similar to how Composer packages are updated.

**Comment by dcblogdev** [comment]
thanks, they were missing from my package.json file. I also didn't have a tailwind config file. Somewhere along the way I've messed something up.

I've installed a fresh app and installed Tall, the package.json file contains the dependencies as you've said.
