### ISSUE TITLE
Issue on "npm install && npm run dev"

### ISSUE THREAD

**Issue by Sintaxis** [laravel-frontend-presets/tall#79]
When i run "npm install && npm run dev" i get below warnings and errors:

vagrant@homestead:~/code/teamsy$ npm install && npm run dev
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN laravel-mix-tailwind@0.1.1 requires a peer of laravel-mix@^2.1.7 but none is installed. You must install peer dependencies yourself.

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/code/teamsy/node_modules/webpack-dev-server/node_modules/ansi-regex/package.json.3885035533
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/code/teamsy/node_modules/webpack-dev-server/node_modules/ansi-regex/package.json.3885035533'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-11-25T13_55_39_251Z-debug.log

And the application fails with error:

"The Mix manifest does not exist"

**Comment by aznj** [comment]
I have same problem when running npm install

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: laravel-mix@5.0.9
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^5.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^2.1.7" from laravel-mix-tailwind@0.1.1
npm ERR! node_modules/laravel-mix-tailwind
npm ERR!   dev laravel-mix-tailwind@"^0.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akmal/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akmal/.npm/_logs/2020-11-26T11_40_02_868Z-debug.log`

**Comment by K2ouMais** [comment]
Same problem here !!!

**Comment by sudoist** [comment]
This is also happening from my fresh install of Laravel 8.
I change "^0.1.0" to "0.1.0" in package.json to get it working.
There could be some issues with latest package.

    "devDependencies": {
        "@tailwindcss/typography": "^0.2",
        "@tailwindcss/ui": "^0.4",
        "alpinejs": "^2.6",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",

        "laravel-mix-tailwind": "0.1.0",

        "resolve-url-loader": "^3.1.0",
        "tailwindcss": "^1.5"
    }

Hope it helps.

**Comment by nathandaly** [comment]
Bump.

**Comment by nathandaly** [comment]
https://github.com/laravel-frontend-presets/tall/issues/86

**Comment by danharrin** [comment]
Hey! Let us know if this issue still persists with v3.0.0.

**Comment by ekandreas** [comment]
Still there
