### ISSUE TITLE
v2.1.1 incompatible with PHP 8

### ISSUE THREAD

**Issue by terrym6263** [laravel-frontend-presets/tall#80]
I installed PHP 8 and received the following error during composer update.

Problem 1
    - Root composer.json requires laravel-frontend-presets/tall ^2.1.1 -> satisfiable by laravel-frontend-presets/tall[v2.1.1].
    - laravel-frontend-presets/tall v2.1.1 requires php ^7.2.5 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by imliam** [comment]
Fixed in #82
