### ISSUE TITLE
Laravel 8.x fresh install: NPM unable to resolve dependency tree

### ISSUE THREAD

**Issue by nathandaly** [laravel-frontend-presets/tall#86]
Fresh Laravel `v8.5.7` installation on MacOs Big Sur and using `^2.2` of the TALL preset.

### Steps to reproduce

`laravel new my-app` or `curl -s https://laravel.build/my-app | bash`
```
composer require livewire/livewire laravel-frontend-presets/tall
php artisan ui tall --auth
npm install
```

### Error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: laravel-mix@6.0.9
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^6.0.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^2.1.7" from laravel-mix-tailwind@0.1.1
npm ERR! node_modules/laravel-mix-tailwind
npm ERR!   dev laravel-mix-tailwind@"^0.1.0" from the root project
```

### Solution

`npm install --force` works but ideally should not error and Tailwind 2.0 should now be the standard..

**Comment by danharrin** [comment]
Hey! Let us know if this issue still persists with v3.0.0.

**Comment by ryatkins** [comment]
I just tried this on a fresh install and still had the same issue.

`npm install --force` did not fix the issue for me.

**Comment by danharrin** [comment]
Hey @ryatkins, does #87 solve your issue?

**Comment by nathandaly** [comment]
not currently unless I am missing something? https://github.com/laravel-frontend-presets/tall/pull/87#issuecomment-761268196
