### ISSUE TITLE
livewire

### ISSUE THREAD

**Issue by Slobug** [laravel-frontend-presets/tall#89]
Hi,

I'm new in Laravel. I test laravel 8 with TALL.

I've a problem : Livewire.js is not in the good place.
the console : vendor/livewire/livewire.js?id=......
my repo : vendor/livewire/livewire/dist/livewire.js

I copied the content of dist/ in vendor/livewire
not enought for work
so, I added a file livewire.php (see in a post) in config/

but now, a message while I use a component : The requested URL /PROJECT/livewire/message/search was not found on this server.

indeed, I've no repo in app/http/livewire

Someone for help me ?

**Comment by imliam** [comment]
> the console : vendor/livewire/livewire.js?id=......

This was referring to the public path being served from your webserver - not from your project's root directory. In your project, this would be `public/vendor/livewire/livewire.js` - NOT `vendor/livewire/livewire/dist.js`.

It should be generated by default if you followed the installation instructions in this package, or the [Livewire installation instructions](https://laravel-livewire.com/docs/2.x/installation).

**Comment by Slobug** [comment]
Oh... I'm sorry.
It works fine !

Thanks a lot.
